AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Adds a favorite set to the user.
Resources:
  PostUserFavoriteFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/postUserFavorites-1.0-SNAPSHOT.jar
      Handler: com.revature.post_user_favorites.PostUserFavoritesHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:iam::011217676466:policy/dynamodb-update-users-item